spring:
  application:
    name: "Config-Dev"

#Configure with eureka registry service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true  # Should be true for clients
    register-with-eureka: true  # Should be true for clients
    service-url:
      defaultZone: http://localhost:8761/eureka  # Points to Eureka server
